version: '2'
services:
  phoenix:
    image: nginx
    ports:
      - "8080:80"
    networks:
      - "fairyland"
    volumes:
      - nest:/mnt
      - ./app/web:/usr/share/nginx/html
  dragon:
    image: nginx
    ports:
      - "8081:80"
    networks:
      - "fairyland"
    volumes:
      - nest:/mnt
      - ./app/web:/usr/share/nginx/html
  monkey:
    image: nginx
    ports:
      - "8082:80"
    networks:
      - "default"
networks:
  fairyland:
    driver: bridge
volumes:
  nest:
    driver: local
